apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: init-all
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: applicationset
    repoURL: >-
      https://github.com/Abdelwaheb-Hnaien/argo
    targetRevision: main
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true