apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: project
spec:
  generators:
  - list:
      elements:
      - app: project
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{app}}'
    spec:
      project: 'default'
      source:
        repoURL: https://github.com/Abdelwaheb-Hnaien/argo.git
        targetRevision: main
        path: project
      ignoreDifferences:
        - group: apps
          jsonPointers:
            - /spec/replicas
          kind: Deployment
      destination:
        server: '{{url}}'
        namespace: "argocd"
    syncPolicy:
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
          - RespectIgnoreDifferences=true
          - CreateNamespace=true